src/Entity/Encuesta.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EncuestaRepository")
 */
class Encuesta
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nombre;

    /**
     * @ORM\Column(type="smallint")
     */
    private $servicio;

    public function getId()
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getServicio(): ?int
    {
        return $this->servicio;
    }

    public function setServicio(int $servicio): self
    {
        $this->servicio = $servicio;

        return $this;
    }

    public static function getArrayServicios() {
        return array(
            'Secretaría General'                            => 1,
            'Administración General y Gestión Económica'    => 2,
            'Gestión de Recursos Humanos'                   => 3,
            'Inspección Educativa'                          => 4,
            'Ordenación Educativa'                          => 5,
            'Planificación y Escolarización'                => 6,
            'Retribuciones'                                 => 7,
        );
    }

    public function getNombreServicio() {
        return array_search($this->servicio, self::getArrayServicios());
    }
}

src/Form/EncuestaType.php
<?php
namespace App\Form;

use App\Entity\Encuesta;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EncuestaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nombre', TextType::class, array(
                'label' => 'Nombre y apellidos',
            ))
            ->add('servicio', ChoiceType::class, array(
                'label'         => 'Dependencia / Servicio',
                'placeholder'   => 'Selecciona un un valor',
                'choices'       => Encuesta::getArrayServicios(),
            ))
        ;
    }
}

src/Controller/EncuestaController.php
<?php
namespace App\Controller;

use App\Entity\Encuesta;
use App\Repository\EncuestaRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use App\Form\EncuestaType;

class EncuestaController extends Controller
{
    /**
     * @Route("/encuesta", name="encuesta_index")
     */
    public function index(Request $request)
    {
        $data = new Encuesta();
        $form = $this->createForm(EncuestaType::class, $data);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $em = $this->getDoctrine()->getManager();
            $em->persist($data);
            $em->flush();

            return $this->redirectToRoute('encuesta_enviada');
        }

        return $this->render('encuesta/index.html.twig', array(
            'form' => $form->createView()
        ));
    }

    /**
     * @Route("/encuesta/enviada", name="encuesta_enviada")
     */
    public function enviada(Request $request)
    {
        return $this->render('encuesta/enviada.html.twig');
    }

    /**
     * @Route("/encuesta/resultados", name="encuesta_resultados")
     */
    public function resultado(EncuestaRepository $encuestas)
    {
        if ($this->isGranted('ROLE_ADMIN') ||
            $this->isGranted('ROLE_ENCUESTAS')) {
            $misEnuestas = $encuestas->findBy(
                [],
                ['servicio' => 'ASC', 'nombre' => 'ASC']
            );

        } else {
            $misEnuestas = null;
        }

        return $this->render('encuesta/list.html.twig', [
            'encuestas' => $misEnuestas,
        ]);
    }

    /**
     * @Route("/encuesta/login", name="encuesta_login")
     */
    public function login (Request $request, AuthenticationUtils $authenticationUtils)
    {

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();

        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('encuesta/login.html.twig', array(
            'last_username' => $lastUsername,
            'error'         => $error,
        ));
    }
}

templates/encuesta/base.html.twig
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>{% block title %}Encuestas{% endblock %}</title>
        {% block stylesheets %}
            <link rel="stylesheet" href="{{ asset('build/css/main.css/') }}">
        {% endblock %}
        <link rel="icon" type="image/x-icon" href="{{ asset('build/favicon.ico') }}" />
    </head>

    {% block header %}
        <header>
            <h1>Confirmación de asistencia a sesión informativa sobre consejo dietético y la práctica recomendable de actividad física</h1>
        </header>
    {% endblock %}

    <div class="container body-container">
        {% block body %}
            <div class="row">
                <div id="main" class="col-sm-9">
                    {{ include('default/_flash_messages.html.twig') }}

                    {% block main %}{% endblock %}
                </div>
            </div>
        {% endblock %}
    </div>

    </body>
</html>

templates/encuesta/enviada.html.twig
{% extends 'encuesta/base.html.twig' %}

{% block body_id 'encuesta_index' %}

{% block main %}
    Gracias por su colaboración
{% endblock %}

templates/encuesta/index.html.twig
{% extends 'encuesta/base.html.twig' %}

{% block body_id 'encuesta_index' %}

{% block main %}
    <p>Lugar:  Delegación Territorial de Educación (Salón de actos del Edificio de Servicios Múltiples )<br>
        Fecha: 28 de junio de 2018<br>
        Hora:   8:00<br>
    </p>
    {{ form_start(form) }}
    {{ form_widget(form) }}

    <button type="submit" class="{{ button_css|default("btn btn-primary") }}">
        <i class="fa fa-save" aria-hidden="true"></i> Confirmar Asistencia
    </button>

    {{ form_end(form) }}
{% endblock %}

templates/encuesta/list.html.twig
{% extends 'encuesta/base.html.twig' %}

{% block body_id 'admin_post_index' %}

{% block main %}
    <h1>Listado de Respuestas</h1>

    <table class="table table-striped table-middle-aligned">
        <thead>
        <tr>
            <th scope="col">Servicio</th>
            <th scope="col">Nombre</th>
        </tr>
        </thead>
        <tbody>
        {% for encuesta in encuestas %}
            <tr>
                <td>{{ encuesta.nombreServicio }}</td>
                <td>{{ encuesta.nombre }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4" align="center">No se han encontrado respuestas</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/encuesta/login.html.twig
{% extends 'encuesta/base.html.twig' %}

{% block body %}
    <h2>
        Para acceder a esta página debes introducir el usuario y contraseña de tu correo corporativo y estar habilitado por el departamento de Proceso de Datos.
    </h2>

    {% if error %}
        <div>{{ error.messageKey|trans(error.messageData, 'security') }}</div>
    {% endif %}

<form action="{{ path('encuesta_login') }}" method="post">
    <label for="username">Usuario:</label>
    <input type="text" id="username" size="40" name="_username" value="{{ last_username }}" placeholder="Identificador de su correo corporativo" />

    <label for="password">Clave:</label>
    <input type="password" id="password" size="40" name="_password" placeholder="Contraseña del correo corporativo"/>

    {#
        If you want to control the URL the user
        is redirected to on success (more details below)
        <input type="hidden" name="_target_path" value="/account" />
    #}

    <button type="submit">login</button>
    </form>{% endblock %}